### ISSUE TITLE
Cannot Sleep

### ISSUE THREAD

**Issue by kebabthief** [blockchaaain/LetMeSleep#1]
**Describe the bug**
With the mod installed, clicking on a bed snaps you to the bed.  Your character lies down, but there's no "Zzzzzz" and you don't sleep and skip the night.

**To Reproduce**
1. Just press E on your bed to reproduce

**Expected behavior**
To sleep and skip the night

**Additional context**
Removing the mod from the Bepinex/plugins folder resolves the problem

**Comment by Martan404** [comment]
Same for me and my friend. Sleeping is completely broken

**Comment by shortybsd** [comment]
Yup due to plugin crash, here is what will be in your logs - [LetMeSleep Crash](https://pastebin.com/s49MPAf2)

**Comment by Martan404** [comment]
I just tried the latest version and it works for me

**Comment by blockchaaain** [comment]
Sorry I did not notice this earlier.
I didn't even know people were using the mod already!

A recent update to Valheim changed some RPC calls.
They have been changing how player info is passed around, to better support multiplatform capabilities it seems.

The mod now uses a much cleaner function call to send out its message.
There is the consequence that it now appears to come from the host player, but this should be "Server" when the host is a dedicated server.

FYI the mod should continue working if showMessage is set to false in the config file.
Even if they keep making changes to messaging.
