### ISSUE TITLE
Config file is blank

### ISSUE THREAD

**Issue by ZenDragonX** [blockchaaain/LetMeSleep#4]
**Describe the bug**
When running the mod the config file is missing all options.

**To Reproduce**
1. Run the mod
2. Open generated config file
3. Notice missing config entries.

**Expected behavior**
There should be config entries.

**Log file**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - Valheim latest
 - BepInEx latest
 - LetMeSleep latest

**Additional context**
N/A

**Comment by blockchaaain** [comment]
Can't reproduce and can't help without log file and version information.
